// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGAQCbdvSheaOWwlnAdNfu2tbV8uRsdxU',
    appId: '1:97920420486:web:8c3eaf4e1fe9d355fadf07',
    messagingSenderId: '97920420486',
    projectId: 'gov-id-1c672',
    authDomain: 'gov-id-1c672.firebaseapp.com',
    storageBucket: 'gov-id-1c672.firebasestorage.app',
    measurementId: 'G-VJGKG4B10X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVZNY6dlk9dXHpzOlmXvqxU87iXSuShtU',
    appId: '1:97920420486:android:1a8cac2fa98a720afadf07',
    messagingSenderId: '97920420486',
    projectId: 'gov-id-1c672',
    storageBucket: 'gov-id-1c672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxl9cNxHkbUWTF2e9neXksctEbQjaTrnQ',
    appId: '1:97920420486:ios:b89798c835c2744cfadf07',
    messagingSenderId: '97920420486',
    projectId: 'gov-id-1c672',
    storageBucket: 'gov-id-1c672.firebasestorage.app',
    iosBundleId: 'com.example.govId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxl9cNxHkbUWTF2e9neXksctEbQjaTrnQ',
    appId: '1:97920420486:ios:b89798c835c2744cfadf07',
    messagingSenderId: '97920420486',
    projectId: 'gov-id-1c672',
    storageBucket: 'gov-id-1c672.firebasestorage.app',
    iosBundleId: 'com.example.govId',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGAQCbdvSheaOWwlnAdNfu2tbV8uRsdxU',
    appId: '1:97920420486:web:b69c0fe21110c3e9fadf07',
    messagingSenderId: '97920420486',
    projectId: 'gov-id-1c672',
    authDomain: 'gov-id-1c672.firebaseapp.com',
    storageBucket: 'gov-id-1c672.firebasestorage.app',
    measurementId: 'G-M5TF555DNE',
  );
}
